---
title: "Stat 450-460: Mathematical statistics I-II"
author: Fall 2017 
---


### [Office hours](Schedule.html)

### Announcements

Take-home midterm is posted and due Wednesday, October 25 by 11:59 pm.

### Resources

  * Additional courses on R provided by [Data Camp](https://www.datacamp.com/)
  * [Base R](https://cran.r-project.org/)
  * [R Studio](https://www.rstudio.com/home/)
  * [ggplot2 cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)  
  * [R Markdown cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)



### Notes

 * Chapter 3: Discrete random variables | [pdf](https://www.dropbox.com/s/dez6w5nqgepexs7/Chapter_3-Discrete.pdf?dl=0) | [Rmd](https://www.dropbox.com/s/2w69winr1hza613/Chapter%203-Discrete.Rmd?dl=0)
 * Chapter 4: Continuous random variables | [pdf](https://www.dropbox.com/s/ao4gsywmreh47hz/Chapter4-continuous.pdf?dl=0) | [Rmd](https://www.dropbox.com/s/7rfb8ovsoplfqnr/Chapter4-continuous.Rmd?dl=0)
 * Chapter 5: Joint distributions | [pdf](https://www.dropbox.com/s/49fvh6czirwj0kj/Chapter5-joint.pdf?dl=0) | [Rmd](https://www.dropbox.com/s/49fvh6czirwj0kj/Chapter5-joint.pdf?dl=0)
 * Chapter 6: Transformations | [pdf](https://www.dropbox.com/s/exqv4o5p6qjlri2/Chapter6-transformations.pdf?dl=0) | [Rmd](https://www.dropbox.com/s/dtjhdymk43m4562/Chapter6-transformations.Rmd?dl=0)

### Exams

This [writing rubric](https://www.dropbox.com/s/0n0vheg0ucg1tln/Writing%20Rubric-2018.docx?dl=0) will be applied to all take-home exams that require the use of R Markdown.  Of your entire midterm grade, 10% of your will come from your score on this rubric; 50% from your score on the take-home portion; and 40% from your score on the in-class portion.  



* [Practice midterm](https://www.dropbox.com/s/sov203yn8i9p6yj/MathStatI-Midterm-Fall2016.docx?dl=0)
* Take-home midterm (due 10/25) | [Word doc](https://www.dropbox.com/s/tcap7bhtf6tfhn7/Stat450-TakeHomeMidterm-Fall2017.docx?dl=0) | [Source file](https://www.dropbox.com/s/lmp8syvoo0xvnzc/Stat450-TakeHomeMidterm-Fall2017.Rmd?dl=0)

### Presentations

<!--
For Monday, 10/30, the following from Chapter 5 (each bullet represents one presentation's worth):

* 77, 92
* 79, 93
* 95, 114
* 136, 141


* 7, 25, 51
* 9, 27, 53
* 11, 29, 55
* 14, 32, 58
-->

### Homework

* [R Homework 1](R_HW1.html) | [.Rmd](https://www.dropbox.com/s/4zsa47cr0031429/R_HW1.Rmd?dl=0)
* [R Homework 2](R_HW2.html) | [.Rmd](https://www.dropbox.com/s/8angsdzqcetqbc6/R_HW2.Rmd?dl=0)
* [R Homework 3](https://www.dropbox.com/s/oyc9p4ixiw5o31c/R_HW3.pdf?dl=0) | [.Rmd](https://www.dropbox.com/s/mpxrssfn93e38u8/R_HW3.Rmd?dl=0) | [Breast cancer data](https://www.dropbox.com/s/b1k99n05s22njvi/BreastCancerSample.csv?dl=0)


The following problems from the textbook are due Monday, 11/20. Hand in solutions at beginning of class.  All of the following are from Chapter 5:


* 14, 15, 17
* 32, 39, 42
* 69, 71
* 86
* 99, 100
* 108, 110, 111
* 142
* 152, 154, 156, 157, 160

<!--
* 6, 15
* 23, 34, 35
* 42
* 80
* 89, 96 (use R on part d.), 111, 112
* 160, 165, 167, 173, 185, 188, 190, 197, 198, 200
-->
