---
title: "R Homework 1"
author: "Stat 450: Fall 2017"
output: html_document
---

**Due Friday, 9/8 by 11:59pm.  Prepare your submission with R Markdown.  Submit fully-knitted html, Word, or pdf to D2L by due date.  You are encouraged to use this .Rmd file as your starting point for your submission.**

In class, we considered the case of rolling two dice, one red and one white.  Let $Y\equiv$ the minimum of the two rolls. 

1.  Define the probability mass function (pmf) in tabular format.  The table is started for you, below.  Fill in the appropriate entries for $p(y)$.

$y$  |  $p(y)$ 
---  | ---
1    |  
2    | 
3    |
4    | 
5    | 
6    |

2.  Graph this pmf.

3. Find $\mu \equiv E(Y)$.

4.  Find $\sigma^2 \equiv Var(Y)$.

5.  Find $M_Y(t)$, and create a plot of $M_Y(t)$ as a function of $t$ over the interval $[-1,1]$.  (Hint: first, write a function `m(t)` that takes as argument `t` and returns $M_Y(t)$, for any input $t$.  Then, create a sequence of $t-$values over $[1,1]$ with the `seq()` function, and use your function to evaluate $M_Y(t)$ for each value in the sequence.  Then plot this sequence with $t$ on the x-axis and $M_Y(t)$ on the y-axis.  The function `exp(t)` can be used to evaluate $e^t$.)

6.  Now write an `R` function `one.Y()` that simulates a single realization of $Y$.  Using this function and `replicate()`, generate 1000 realizations of $Y$.  Graph the empirical pmf, and verify that is is similar to the theoretical one above.

7.  Find the empirical mean $\bar Y$ and variance $S^2$ (use `mean()` and `var()`).  How do they compare to $\mu$ and $\sigma^2$?


