---
title: "Syllabus"
output: html_document
---

### STAT 450-460: Mathematical statistics I-II
### Fall 2017
### INSTRUCTOR: Dr. Silas Bergen
### OFFICE: Gildemeister 124D
### [Office hours](Schedule.html)



### Prerequisites:
  * Math 312 (Multivariable calculus)
  * Math 337 (Probability); concurrent enrollment OK
  * Eng 111

### Course summary

STAT 450 and 460 are courses in mathematical statistics intended for upper-level undergraduate students in the mathematical sciences. The goal in STAT 450 is provide a solid foundation in the theory of random variables, probability distributions, and convergence in probability and distribution. The successful student in STAT 460 will leave the course with a basic understanding of many of the important foundational concepts in statistical inference, namely estimation (with confidence) and hypothesis testing. In addition, students will be comfortable using a wide variety of mathematical tools for solving statistical inference problems. 

Along the way, students will also become adept at using R to investigate and solve statistical problems.  

### Course text

The required text for this course is Mathematical Statistics with Applications by Wackerly, Mendenhall, & Scheaffer, 7th edition (WMS7).  Students may share copies of this book, although students planning on continuing to graduate school are encouraged to have their own copy.  

* [Amazon link](https://www.amazon.com/Mathematical-Statistics-Applications-Dennis-Wackerly/dp/0495110817/ref=sr_1_1?ie=UTF8&qid=1471463588&sr=8-1&keywords=mathematical+statistics+wackerly)
* [Kindle version](http://web.csulb.edu/~okoroste/wackerly.pdf)


###  Course outline 

 * Ch. 1 - What is Statistics? (review)
 * Ch. 2 - Probability (review)
 * Ch. 3 - Discrete Random Variables (review)
 * Ch. 4 - Continuous Random Variables (review)
 * Ch. 5 - Bivariate and Multivariate Distributions 	
 * Ch. 6 - Functions of Random Variables 	
 * Ch. 7 - Sampling Distributions and the CLT 	
 * Ch. 8 - Estimation 	
 * Ch. 9 - Properties of Point Estimators and Methods of Estimation 	
 * Ch. 10 - Hypothesis Testing 	
 * Ch. 16 - Introduction to Bayesian Methods for Inference
 * Other Chapters and Topics (time permitting) 	Selected topics and sections from Ch. 11 - 15 and others not included in the text, e.g. resampling methods.
 
##  Statistical computing

We will use the open-source R programming language extensively throughout this course, both in the course notes and through regular R-specific assignments.   Please download R and R studio using the links below.

  * [Base R](https://cran.r-project.org/)
  * [R Studio](https://www.rstudio.com/home/)
  * [ggplot2 cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)  
  * [R Markdown cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

## Assignments

Your final grade will be determined based on the following criteria:

***Presentations (10%)*** 

On a regular basis throughout the semester, I will assign problems that you will be required to present to the class.  These may be either problems from the textbook, or additional problems that I assign.  You will have at least 2 days to work on the problem before presenting.

***Homework (40%)***

Submitted homework will be comprised of two parts:

  1. *Theoretical problems:* These will primarily be problems assigned from WMS7.  Students are encouraged, but not required, to submit these homework solutions using R Markdown/LaTeX.   
  2. *Investigative problems:* In addition to the theoretical problems, there will be regular problems that require the use of R to investigate some aspect of the content covered in class.  ***Solutions to these assignments must be submitted as a knitted html document.*** 


***Midterm exam (25%)***

The Midterm exam will likely comprise both an in-class and take-home portion, with the in-class involving more theoretical problems and the take-home more computational problems.  

***Final exam (25%)***

Similar to the Midterm, the Final exam will likely comprise both an in-class and take-home portion, with the in-class involving more theoretical problems and the take-home more computational problems.  
